# Created using wingetcreate 1.6.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Arm.WindowsPerf
PackageVersion: 3.8.0.0
InstallerLocale: en-US
InstallerType: wix
ProductCode: '{1ACE4754-BF60-454A-9E6D-861DE875AE83}'
Installers:
- InstallerUrl: https://gitlab.com/api/v4/projects/40381146/packages/generic/windowsperf/3.8.0/wperf-installer.msi
  Architecture: arm64
  InstallerSha256: C96B1DAEE6E2690829E36533AD2F308031CB688F5DBC0E78E14A6E74BBCC07E1
ManifestType: installer
ManifestVersion: 1.6.0
